server:
  port: 8085
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME:localhost:3306}/${RDS_DB_NAME:spada}?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ${RDS_USERNAME:root}
    password: ${RDS_PASSWORD:Qweasd123}
  redis:
    host: ${REDIS_HOSTNAME:localhost} # địa chỉ máy chủ Redis
    database: 0 # Redis chỉ mục cơ sở dữ liệu (mặc định là 0)
    port: 6379 # Redis cổng kết nối máy chủ
    password: # Redis mật khẩu kết nối máy chủ (mặc định trống)
    jedis:
      pool:
        max-active: 8 # Số lượng kết nối tối đa trong nhóm kết nối (sử dụng các giá trị âm để biểu thị không giới hạn)
        max-wait: -1ms # Thời gian chờ chặn tối đa của nhóm kết nối (sử dụng giá trị âm có nghĩa là không giới hạn)
        max-idle: 8 # Kết nối nhàn rỗi lớn nhất trong nhóm kết nối
        min-idle: 0 # Kết nối nhàn rỗi nhỏ nhất trong nhóm kết nối
    timeout: 3000ms # thời gian chờ kết nối (ms)
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: ${ELS_HOSTNAME:localhost}:9300 # es địa chỉ kết nối và số cổng
      cluster-name: ${ELS_CLUSTERNAME:elasticsearch}
    mongodb:
      host:  ${MONGODB_HOSTNAME:localhost} # địa chỉ kết nối localhost # mongodb
      port: 27017  # số cổng kết nối mongodb
      database: mall-port # cơ sở dữ liệu mongodb : mall-port
    rabbitmq:
      host: ${RBMQ_HOSTNAME:localhost} # địa chỉ kết nối localhost
      port: 15672 # rabbitmq số cổng kết nối
      virtual-host: /mall # rabbitmq máy chủ ảo
      username: mall # rabbitmq tên người dùng
      password: iloveyoyo # rabbitmq mật khẩu
      publisher-confirms: true #Nếu yêu cầu gọi lại cho các tin nhắn không đồng bộ, nó phải được đặt thành true

elasticsearch:
  index-name: "pms"
  user-type: "product"
  host: "localhost"
  port: 9200
  username: ""
  password: ""

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

#Tùy chỉnh redis key
redis:
  key:
    string:
      prefix: "portal:authCode:"
      expire: 120
      emptyValidate: "Vui lòng nhập mã xác minh"
      getValidate: "Lấy mã xác minh thành công"
      successValidate: "Xác minh mã xác thực đã thành công"
      failValidate: "Mã xác minh không chính xác"

# Tùy chỉnh JWT key
jwt:
  tokenHeader: Authorization #JWT Tiêu đề yêu cầu được lưu trữ
  secret: mySecret #JWT Khóa được sử dụng để mã hóa và giải mã
  expiration: 604800 #JWT Expire Time (60 * 60 * 24)
  tokenHead: ""  #JWT Bắt đầu tải

